server.contextPath=/temporarystall-services
server.port=8080

#timeZone
app.timezone=UTC

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://13.71.2.192:5432/digit_dev_db
spring.datasource.username=digit_chd
spring.datasource.password=digit@chd_2021


##----------------------------- FLYWAY CONFIGURATIONS ------------------------------#
flyway.url=jdbc:postgresql://13.71.2.192:5432/digit_dev_db
flyway.user=digit_chd
flyway.password=digit@chd_2021
flyway.table=public
flyway.baseline-on-migrate=true
flyway.outOfOrder=true
flyway.locations=db/migration/main
flyway.enabled=true



# Kafka Configuration
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

#kafka.config.bootstrap_server_config=192.168.12.124:9092
#spring.kafka.bootstrap-servers=192.168.12.124:9092

##----------------------------- KAFKA SERVER CONFIGURATIONS ------------------------------#

kafka.config.bootstrap_server_config=192.168.12.124:9092
spring.kafka.bootstrap-servers=192.168.12.124:9092

#logger Configuration
logging.pattern.console=%clr(%X{CORRELATION_ID:-}) %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}
logging.level.org.egov=DEBUG

#mdms urls


egov.mdms.host=https://egov.chandigarhsmartcity.in/
egov.mdms.search.endpoint=egov-mdms-service/v1/_search

#Idgen Config
egov.idgen.host=https://egov.chandigarhsmartcity.in/
egov.idgen.path=egov-idgen/id/_generate


#egov.idgen.host=https://egov.chandigarhsmartcity.in/
#egov.idgen.path=egov-idgen/id/_generate




egov.idgen.temporary.stall.idname=ch.temp.stall
egov.idgen.temporary.stall.idformat=CH-TS/[fy:yyyy-yy]/[SEQ_TEMP_STALL_ID_GEN]


# Kafka Topics-sep topics
persister.save.stallapplication.topic=save-stallapplication

egov.demand.minimum.payable.amount = 100

persister.update.stallapplication.topic=update-stallapplication

persister.update.stallapplication.paymentstatus.topic=update-stallapplication-payment
persister.update.stallapplication.applicationstatus.topic=update-stallapplication-application



#...........................Billing Service Demand configs.........................#
egov.billingservice.host=https://egov.chandigarhsmartcity.in

egov.demand.create.endpoint=/billing-service/demand/_create
egov.demand.update.endpoint=/billing-service/demand/_update
egov.demand.search.endpoint=/billing-service/demand/_search?
egov.services.billing_service.search=/billing-service/bill/v2/_search
egov.bill.gen.endpoint=/billing-service/bill/v2/_fetchbill

egov.collectionservice.host=https://egov.chandigarhsmartcity.in/
egov.collection.search.endpoint=collection-services/payments/_search?
