tracer.errors.provideExceptionInDetails=false
server.port=8081
server.context-path=/horticulture-services
app.timezone=UTC

#actuator config
endpoints.beans.id=springbeans
endpoints.beans.sensitive=true
endpoints.beans.enabled=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://13.71.2.192:5432/digit_dev_db
spring.datasource.username=postgres
spring.datasource.password=dev_pG%P@ssw0rd

#----------------------------- FLYWAY CONFIGURATIONS ------------------------------#
flyway.url=jdbc:postgresql://13.71.2.192:5432/digit_dev_db
flyway.user=postgres
flyway.password=dev_pG%P@ssw0rd
flyway.table=public
flyway.baseline-on-migrate=true
flyway.outOfOrder=true

#flyway.locations=db/migration/main,db/migration/seed

flyway.locations=db/migration/main
flyway.enabled=false

#-------------------Kafka----------------------------#
# KAFKA SERVER CONFIGURATIONS
kafka.config.bootstrap_server_config=192.168.12.145:9092

# SPRING KAFKA CONSUMER CONFIGURATIONS
spring.kafka.consumer.value-deserializer=org.egov.tracer.kafka.deserializer.HashMapDeserializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.group-id=horticulture-services

# SPRING KAFKA PRODUCER CONFIGURATIONS
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# KAFKA PRODUCER CONFIGURATIONS
kafka.producer.config.retries_config=0
kafka.producer.config.batch_size_config=16384
kafka.producer.config.linger_ms_config=1
kafka.producer.config.buffer_memory_config=33554432

kafka.topics.notification.sms=egov.core.notification.sms
kafka.topics.notification.email=egov.core.notification.email

date.format.notification=dd-MMM-yyyy

#-------- Notification Injection switch------#

notification.sms.enabled=true
notification.email.enabled=true
egov.usr.events.notification.enabled=true

#SLA days configration
egov.horticulture.sla.daysconfig = 4

notification.allowed.on.status=EDITED,OPEN,REJECT,INSPECT,APPROVE,ASSIGN,COMPLETE,REQUESTCLARIFICATION,VERIFYANDFORWARD,INITIATE,UPDATE,VERIFYANDFORWARDTOSDO,FORWARDFORINSPECTION,INITIATED,VERIFYFORCLOSURE,FORWARDFORCOMPLETION
notification.fallback.locale=en_IN


#................egov-usr-events configs.......................#
egov.usr.events.create.topic=persist-user-events-async
egov.ui.app.host=https://egov-micro-dev.egovernments.org

egov.mdms.host=https://egov-dev.chandigarhsmartcity.in
egov.mdms.get.endpoint=/egov-mdms-service/v1/_gets
egov.mdms.search.endpoint=/egov-mdms-service/v1/_search

#localization urls
egov.localization.host=https://egov-dev.chandigarhsmartcity.in
egov.localization.search.endpoint=/localization/messages/v1/_search

#HRMS
egov.hrms.host=https://egov-dev.chandigarhsmartcity.in
egov.hrms.search.endpoint=/egov-hrms/employees/_search


#user
egov.user.host=https://egov-dev.chandigarhsmartcity.in
egov.user.search.endpoint=/user/_search
egov.user.create.endpoint=/user/users/_createnovalidate

#Idgen Config

egov.idgen.host=https://egov-dev.chandigarhsmartcity.in/
egov.idgen.path=egov-idgen/id/_generate
egov.idgen.horticulture.serviceRequestNum.name.mcc=ch.hc
egov.idgen.horticulture.serviceRequestNum.format.mcc=CH-HC-[cy:yyyy-MM-dd]-[SEQ_EG_HC_APL]
egov.idgen.horticulture.serviceRequestNum.name.ut=ch.hc.ut
egov.idgen.horticulture.serviceRequestNum.format.ut=CHD-HC-[cy:yyyy-MM-dd]-[SEQ_EG_HC_APL]
egov.idgen.horticulture.serviceRequestNum.name.forest=ch.hc.fr
egov.idgen.horticulture.serviceRequestNum.format.forest=CHD-HC-[cy:yyyy-MM-dd]-[SEQ_EG_HC_APL]


# workflow config
is.external.workflow.enabled=true

# wf url
workflow.context.path=https://egov-dev.chandigarhsmartcity.in/
workflow.transition.path=egov-workflow-v2/egov-wf/process/_transition
workflow.process.search.path=/egov-workflow-v2/egov-wf/process/_search
workflow.businessservice.search.path=egov-workflow-v2/egov-wf/businessservice/_search


# horticulture-service-request kafka topic

kafka.topics.save.service=horticulture-services-save
kafka.topics.update.service=horticulture-service-update
kafka.topics.update.status.service=horticulture-service-edit
kafka.topics.update.serviceRequest.service=horticulture-services-editSeviceRequestType
kafka.topics.deleteDoc.service=horticulture-service-delete-doc

#Device Source
kafka.insert.request.device.source=horticulture-services-request-device-source

persister.save.transition.wf.topic=save-wf-transitions

logging.level.org.springframework=ERROR
logging.level.org.egov=INFO

#Pagination
egov.horticulture.default.offset=0
egov.horticulture.default.limit=1000
egov.horticulture.max.limit=1000

#Search parameter Config
citizen.allowed.search.params=tenantId,service_request_id,limit,offset,fromDate,toDate,createdtime,service_type
employee.allowed.search.params=tenantId,service_request_id,Status,contactNumber,fromDate,toDate,serviceType,actions,limit,offset

#validation file reading
egov.validation.addupdate.json.path=classpath:config/horticulture-json-validator.json

#sms template details
egov.horticulture.sms.template=Horticulture Service request Id: <service_request_id> has been APPROVED. This message is for necessary information. Regards,Horticulture Department.



