server.contextPath=/sterilizationdog-services
server.port=8080

#timeZone
app.timezone=UTC

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://13.71.2.192:5432/digit_dev_db
spring.datasource.username=digit_chd
spring.datasource.password=digit@chd_2021

##----------------------------- FLYWAY CONFIGURATIONS ------------------------------#
flyway.url=jdbc:postgresql://13.71.2.192:5432/digit_dev_db
flyway.user=digit_chd
flyway.password=digit@chd_2021
flyway.table=public
flyway.baseline-on-migrate=true
flyway.outOfOrder=true
flyway.locations=db/migration/main
flyway.enabled=true


# Kafka Configuration
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

#kafka.config.bootstrap_server_config=192.168.12.124:9092
#spring.kafka.bootstrap-servers=192.168.12.124:9092

##----------------------------- KAFKA SERVER CONFIGURATIONS ------------------------------#

kafka.config.bootstrap_server_config=192.168.12.124:9092
spring.kafka.bootstrap-servers=192.168.12.124:9092

#logger Configuration
logging.pattern.console=%clr(%X{CORRELATION_ID:-}) %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}
logging.level.org.egov=DEBUG


#Idgen Config
egov.idgen.host=https://egov-dev.chandigarhsmartcity.in/
egov.idgen.path=egov-idgen/id/_generate

egov.idgen.sterilization.dog.idname=ch.sterilization.dog
egov.idgen.sterilization.dog.idformat=CH-DS/[fy:yyyy-yy]/[SEQ_STERILIZATION_DOG_ID_GEN]

# Kafka Topics-sterilization dog topics
persister.save.sterilizationdogapplication.topic=save-sterilizationdogapplication
persister.update.sterilizationdogapplication.topic=update-sterilizationdogapplication
